// @vitest-environment jsdom

import { cleanup, render } from "@testing-library/react";
import { afterEach, describe, expect, it } from "vitest";
import StreamingMarkdown from "../src/renderer/components/StreamingMarkdown";

afterEach(() => {
	cleanup();
});

describe("StreamingMarkdown glob escaping", () => {
	it("renders *.md file globs literally without italicising the middle", () => {
		const content =
			"从 ~/.pi/agent/agents/*.md 或 .pi/agents/*.md 加载 agent 定义";
		render(<StreamingMarkdown content={content} />);
		const paragraph = document.querySelector("p");
		expect(paragraph?.textContent).toBe(content);
		// No <em> should be generated by the asterisks.
		expect(document.querySelector("em")).toBeNull();
	});

	it("preserves normal emphasis markers like *italic*", () => {
		const content = "这是 *斜体* 文本";
		render(<StreamingMarkdown content={content} />);
		const em = document.querySelector("em");
		expect(em).not.toBeNull();
		expect(em?.textContent).toBe("斜体");
	});

	it("does not escape globs inside fenced code blocks", () => {
		const content = "```text\n*.md\n```";
		render(<StreamingMarkdown content={content} />);
		const pre = document.querySelector("pre");
		expect(pre).not.toBeNull();
		expect(pre?.textContent).toContain("*.md");
		// The backslash escape should not appear inside the code block.
		expect(pre?.textContent).not.toContain("\\*.md");
	});
});
