// Shared package entry point — re-exports non-React modules.
// UI components remain available via subpath imports (e.g. @look/shared/components/ui/button).

export { AgentTag } from "./components/AgentTag.js";
export { ErrorBoundary } from "./components/ErrorBoundary.js";
export { FileTag } from "./components/FileTag.js";
export { McpTag } from "./components/McpTag.js";
export { SkillTag } from "./components/SkillTag.js";
// Generic UI components
export { default as UserAvatar } from "./components/UserAvatar.js";
export { cn } from "./lib/utils.js";
export {
	ensureLookDir,
	ensureProjectDir,
	ensureProjectSharedDir,
	ensureWorkspaceDir,
	ensureWorkspaceSubsessionsDir,
	getAuthPath,
	getCustomProvidersPath,
	getDefaultWorkspaceCwd,
	getLookDir,
	getModelsPath,
	getProjectDir,
	getProjectSettingsPath,
	getProjectSharedDir,
	getProjectSystemPromptPath,
	getProjectsIndexPath,
	getPromptsPath,
	getScheduledTaskLocksDir,
	getScheduledTasksPath,
	getSessionsDir,
	getSettingsPath,
	getSharedAreasDir,
	getSystemPromptPath,
	getUiSettingsPath,
	getUserProfilePath,
	getWorkspaceDir,
	getWorkspaceSessionsDir,
	getWorkspaceSubsessionsDir,
	getWorkspacesDir,
	resetLegacySessionsOnce,
	sanitiseWorkspaceName,
} from "./look-storage.js";
export { DEFAULT_SESSION_NAME } from "./session-defaults.js";
export type {
	AgentDefinitionInfo,
	AgentDefinitionInput,
	AgentDefinitionSource,
	AgentInfo,
	AvailableModel,
	EventCallback,
	FileTreeNode,
	ForkedSessionResult,
	ImSessionProvider,
	LookMessageDurationEntryData,
	LookTone,
	LookUiEvent,
	LookUiPhase,
	LookUiToolExecState,
	MainToRendererEvent,
	NavigateTreeResult,
	PermissionAskEvent,
	PermissionAskQueueItem,
	PermissionMode,
	PermissionRespondPayload,
	PlanApprovalOutcome,
	PlanApprovalRequest,
	PlanApprovalResponse,
	PlanQuestion,
	PlanQuestionOption,
	PlanQuestionOutcome,
	PlanQuestionRequest,
	PlanQuestionResponse,
	ProjectInfo,
	ProviderInfo,
	RendererToMainEvent,
	ScheduledTask,
	ScheduledTaskInput,
	ScheduledTaskNotification,
	ScheduledTaskRetryPolicy,
	ScheduledTaskRunLog,
	ScheduledTaskRunStatus,
	ScheduledTaskSchedule,
	ScheduledTaskStatus,
	ScheduledTaskTestResult,
	SessionRuntimeSnapshot,
	SessionSnapshotEnvelope,
	SessionUiEventEnvelope,
	TaskExecutionProfile,
	TaskRun,
	TaskRunSource,
	ThinkingLevel,
	ToolCallHandler,
	UILanguage,
	UserProfile,
	UserSettings,
} from "./types.js";
