// Shared package entry point — types, storage helpers, and domain contracts.
// UI components have moved to @look/ui.

export type {
	InvokeResponse,
	InvokeResponseMap,
	InvokeResult,
} from "./contracts/invoke-response.js";
export type { IpcResult } from "./contracts/ipc.js";
export {
	DEFAULT_LOOK_THEME,
	getLookThemeWindowBackground,
	isLookThemeStyle,
	isLookTone,
	LOOK_THEME_LEGACY_MAP,
	LOOK_THEME_STYLE_VALUES,
	LOOK_TONE_VALUES,
	resolveLookTheme,
} from "./contracts/settings.js";
export {
	ensureLookDir,
	ensureProjectDir,
	ensureProjectSharedDir,
	ensureWorkspaceDir,
	ensureWorkspaceSubsessionsDir,
	getAuthPath,
	getCustomProvidersPath,
	getDefaultWorkspaceCwd,
	getDraftsPath,
	getLookDir,
	getModelsPath,
	getProjectDir,
	getProjectSettingsPath,
	getProjectSharedDir,
	getProjectSystemPromptPath,
	getProjectsIndexPath,
	getPromptsPath,
	getScheduledTaskLocksDir,
	getScheduledTasksPath,
	getSessionsDir,
	getSettingsPath,
	getSharedAreasDir,
	getSystemPromptPath,
	getUiSettingsPath,
	getUserProfilePath,
	getWorkspaceDir,
	getWorkspaceSessionsDir,
	getWorkspaceSubsessionsDir,
	getWorkspacesDir,
	resetLegacySessionsOnce,
	sanitiseWorkspaceName,
} from "./look-storage.js";
export { maskSecret } from "./secret-mask.js";
export { DEFAULT_SESSION_NAME } from "./session-defaults.js";
export type {
	AgentDefinitionInfo,
	AgentDefinitionInput,
	AgentDefinitionSource,
	AgentInfo,
	AppUpdatePhase,
	AvailableModel,
	BrowserViewBounds,
	BrowserViewLayout,
	CustomProviderInput,
	CustomProviderModelInput,
	EventCallback,
	FileTreeNode,
	ForkedSessionResult,
	ImSessionProvider,
	LookMessageDurationEntryData,
	LookTheme,
	LookThemeStyle,
	LookTone,
	LookUiEvent,
	LookUiPhase,
	LookUiToolExecState,
	MainToRendererEvent,
	NavigateTreeResult,
	PermissionAskEvent,
	PermissionAskQueueItem,
	PermissionMode,
	PermissionRespondPayload,
	PlanApprovalOutcome,
	PlanApprovalRequest,
	PlanApprovalResponse,
	PlanQuestion,
	PlanQuestionOption,
	PlanQuestionOutcome,
	PlanQuestionRequest,
	PlanQuestionResponse,
	ProjectInfo,
	ProviderInfo,
	RendererToMainEvent,
	ScheduledTask,
	ScheduledTaskInput,
	ScheduledTaskNotification,
	ScheduledTaskRetryPolicy,
	ScheduledTaskRunLog,
	ScheduledTaskRunStatus,
	ScheduledTaskSchedule,
	ScheduledTaskStatus,
	ScheduledTaskTestResult,
	SessionRuntimeSnapshot,
	SessionSnapshotEnvelope,
	SessionUiEventEnvelope,
	TaskExecutionProfile,
	TaskRun,
	TaskRunSource,
	ThinkingLevel,
	ToolCallHandler,
	UILanguage,
	UserProfile,
	UserSettings,
} from "./types.js";
